/*
 * Engine: HSQLDB
 * Version: 0.0.1
 * Description: Initial database structure and data.
 */

/*
 * Structure
 */
create table Bitcoin (
  id bigint generated by default as identity (start with 1 increment by 1) not null,
  referenceId varchar(255) not null,
  version int not null,
  createdAt datetime not null,
  updatedAt datetime default null,
  disclaimer varchar(2000) not null,
  chartName varchar(255),
  updatedTime datetime not null,
  rate float not null;
  primary key (id),
  constraint uq_Account_ReferenceId unique (referenceId)
);

